user root;
worker_processes 1;

events {
    worker_connections 1024;
}


http {
    server_tokens off;
    charset utf-8;

    # always redirect to https
    server {
        listen 80;
        server_name opinix.ru www.opinix.ru;

        # редирект всех запросов на HTTPS
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;

        server_name opinix.ru www.opinix.ru;

        ssl_certificate /etc/ssl/opinix.crt;
        ssl_certificate_key /etc/ssl/opinix.key;

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;

        location /api/ {
            proxy_pass http://opinix:8080/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection keep-alive;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            proxy_pass http://client:3000;
        }

    }
}